PinwheelSDK/Classes/Pinwheel.swift

Allow window.open so forgot password flows work.

---

Example/Podfile
Example/Podfile.lock

Bump nimble version to pick up [build fix](https://github.com/Quick/Nimble/pull/863)
> Fix [#1]()

Bump nimble version to pick up build fix

---

PinwheelSDK.podspec

Merging version bump back
> Fix [#1]()

Release 2.3.2

---

Sources/PinwheelSDK/Classes/Pinwheel.swift

The `WKUserContentController` [strongly retains](https://stackoverflow.com/questions/26383031/wkwebview-causes-my-view-controller-to-leak) script message handlers that are added to it in `loadView`. This causes a retain cycle where `PinwheelViewController` has a strong reference to its `webView` and the `webView` has a strong reference back to `PinwheelViewController` through the userContentController. You can test this by running the Example app in the PinwheelSDK workspace and profiling the allocations within Instruments. Each time "Fetch Link Token" is tapped, the number of `PinwheelViewController` instances increases. These script message handlers should be explicitly removed when the `PinwheelViewController` is dismissed.
This PR introduces a discrete private object …

Fix retain cycle caused by script message handlers

---

Makefile
README.md
scripts/feature.sh

Adding a new make feature command to pinwheel-ios-sdk. This will make tracking development in Jira easier.
- [*] New feature (non-breaking change that adds functionality)
> Fix [#1]()

Adding the make feature command to pinwheel-ios-sdk

---

PinwheelSDK.podspec
Sources/PinwheelSDK/Classes/Pinwheel.swift

Pulling release back to master

Release 2.3.4

---

Makefile
README.md
scripts/feature.sh

Fixing small bug in make feature script caused by faulty copy pasting :)
- [*] New feature (non-breaking change that adds functionality)
> Fix [#1]() 
- [*] Lint rules pass locally
- [*] The code changed/added as part of this pull request has been covered with tests
- [*] All tests related to the changed code pass in development
- [*]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [*] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [*] Changes have been reviewed by at least one other engineer
- [*] Issue from task tracker has a link to this pull request

Fixing small bug in make feature script

---

PinwheelSDK.podspec
Sources/PinwheelSDK/Classes/Pinwheel.swift

Release 2.3.5

---

Example/PinwheelSDK.xcodeproj/project.pbxproj
Example/PinwheelSDK.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Example/PinwheelSDK.xcodeproj/xcshareddata/xcschemes/PinwheelSDK-Example.xcscheme
Example/PinwheelSDK.xcodeproj/xcshareddata/xcschemes/PinwheelSDK_Tests.xcscheme
Example/PinwheelSDK/Base.lproj/Main.storyboard
Example/PinwheelSDK/EventData.swift
Example/PinwheelSDK/EventsTableViewController.swift
Example/PinwheelSDK/LinkConfigTableViewController.swift
Example/PinwheelSDK_ExampleUITests/Info.plist
Example/PinwheelSDK_ExampleUITests/PinwheelSDK_ExampleUITests.swift
PinwheelSDK.podspec
Sources/PinwheelSDK/Classes/Pinwheel.swift

Adds a basic UI test including a basic event verification screen
PP-5486
PP-5548

Add UI Basic UI test

---

.gitignore
Example/PinwheelSDK.xcodeproj/project.pbxproj
Example/PinwheelSDK/APISecret.swift.gyb
Example/PinwheelSDK/LinkToken.swift
Example/Podfile.lock
README.md
env-vars.example.sh
scripts/gyb
scripts/gyb.py

This PR updates the build to read the api secret from an environment variable, then use gyb to generate the relevant swift code.

Use environment variable for api secret.

---

Example/PinwheelSDK/LinkConfigTableViewController.swift
Example/Tests/Tests.swift
Sources/PinwheelSDK/Classes/Events/PinwheelEventType.swift
Sources/PinwheelSDK/Classes/Events/PinwheelLoginAttemptEvent.swift
Sources/PinwheelSDK/Classes/Events/PinwheelLoginAttemptPayload.swift
Sources/PinwheelSDK/Classes/Pinwheel.swift

Add support for login_attempt event

Add support for login_attempt event

---

.gitignore
Example/PinwheelSDK_ExampleUITests/PinwheelSDK_ExampleUITests.swift

Add exit assertion

---

PinwheelSDK.podspec
Sources/PinwheelSDK/Classes/Pinwheel.swift

Release #47 add platformId to success event payload

Release 2.3.9

---

Example/PinwheelSDK/LinkConfigTableViewController.swift
Example/Tests/Tests.swift
Sources/PinwheelSDK/Classes/Events/PinwheelEventType.swift
Sources/PinwheelSDK/Classes/Pinwheel.swift

Add support for input_required event

---

CHANGELOG.md
Example/PinwheelSDK.xcodeproj/project.pbxproj
PinwheelSDK.podspec
Sources/PinwheelSDK/Classes/Pinwheel.swift

- Fixed bug where PinwheelEventType.inputRequired was not being sent.
- Added by [Robby Abaya](https://github.com/rawbee) in Pull Request [#54](https://github.com/underdog-tech/pinwheel-ios-sdk/pull/54).

Release 2.3.11

---

CHANGELOG.md

Link to releases in changelog

---

Example/PinwheelSDK.xcodeproj/project.pbxproj
Example/PinwheelSDK.xcodeproj/xcshareddata/xcschemes/PinwheelSDK-Example.xcscheme
Example/PinwheelSDK.xcodeproj/xcshareddata/xcschemes/PinwheelSDK_Tests.xcscheme
Example/PinwheelSDK.xcodeproj/xcshareddata/xcschemes/PinwheelSDK_UITests.xcscheme
Example/PinwheelSDK/LinkToken.swift
Example/PinwheelSDK_ExampleUITests/Info.plist
Example/Podfile
Example/Podfile.lock
Sources/PinwheelSDK/Classes/Pinwheel.swift

- Changes the PinwheelDelegate reference to be optional and weak.

Make delegate reference weak

---

CHANGELOG.md
PinwheelSDK.podspec
Sources/PinwheelSDK/Classes/Pinwheel.swift

Release 2.3.12

---

CHANGELOG.md
PinwheelSDK.podspec
Sources/PinwheelSDK/Classes/Pinwheel.swift

Release 2.3.13

---

Example/PinwheelSDK/EventData.swift
Example/PinwheelSDK/EventsTableViewController.swift
Example/PinwheelSDK/LinkConfigTableViewController.swift
Example/PinwheelSDK/LinkToken.swift
Example/Podfile.lock
Example/Tests/Tests.swift
Sources/PinwheelSDK/Classes/Events/PinwheelAllocation.swift
Sources/PinwheelSDK/Classes/Events/PinwheelAmountPayload.swift
Sources/PinwheelSDK/Classes/Events/PinwheelError.swift
Sources/PinwheelSDK/Classes/Events/PinwheelErrorEvent.swift
Sources/PinwheelSDK/Classes/Events/PinwheelEventType.swift
Sources/PinwheelSDK/Classes/Events/PinwheelExitEvent.swift
Sources/PinwheelSDK/Classes/Events/PinwheelExitPayload.swift
Sources/PinwheelSDK/Classes/Events/PinwheelInputAllocationEvent.swift
Sources/PinwheelSDK/Classes/Events/PinwheelInputAllocationPayload.swift
Sources/PinwheelSDK/Classes/Events/PinwheelInputAmountEvent.swift
Sources/PinwheelSDK/Classes/Events/PinwheelLoginAttemptEvent.swift
Sources/PinwheelSDK/Classes/Events/PinwheelLoginAttemptPayload.swift
Sources/PinwheelSDK/Classes/Events/PinwheelLoginEvent.swift
Sources/PinwheelSDK/Classes/Events/PinwheelLoginPayload.swift
Sources/PinwheelSDK/Classes/Events/PinwheelParams.swift
Sources/PinwheelSDK/Classes/Events/PinwheelSelectedEmployerEvent.swift
Sources/PinwheelSDK/Classes/Events/PinwheelSelectedEmployerPayload.swift
Sources/PinwheelSDK/Classes/Events/PinwheelSelectedPlatformEvent.swift
Sources/PinwheelSDK/Classes/Events/PinwheelSelectedPlatformPayload.swift
Sources/PinwheelSDK/Classes/Events/PinwheelSuccessEvent.swift
Sources/PinwheelSDK/Classes/Events/PinwheelSuccessPayload.swift
Sources/PinwheelSDK/Classes/Pinwheel.swift

> Description here
> Fix [#1]()

Updated event system

---

Sources/PinwheelSDK/Classes/Events/PinwheelAllocation.swift
Sources/PinwheelSDK/Classes/Events/PinwheelTarget.swift

Add `target` to `PinwheelAllocation`
> Fix [#1]()

Add target field to PinwheelAllocation

---

.editorconfig
.github/CODEOWNERS
.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/documentation-issue-report.md
.github/ISSUE_TEMPLATE/feature-request.md
SECURITY.md

This sets up a few pieces:
* A `.editorconfig` file to help keep consistent config across dev environments (ref: https://editorconfig.org/)
* Assigned the code ownership to an entire team
* Added a few issue templates to help with reports

feat: Set up a few pieces of repo boilerplate

---

scripts/create-pr.sh
scripts/install-aws-mac.sh

Update pr logic (Abort manually)

---

scripts/install-aws-mac.sh

Fix aws-cli install

---

.circleci/config.yml

Fix caching in CI

---

scripts/create-pr.sh
scripts/helpers.sh
scripts/release-github.sh

Add function set_up_github_user

Add function set_up_github_user

---

scripts/create-pr.sh
scripts/helpers.sh

Use authenticated origin

---

.circleci/config.yml
scripts/create-pr.sh

Create PR correctly

---

scripts/create-pr.sh

Push force always

---

scripts/create-pr.sh

Use correct branch name in CI

---

scripts/create-pr.sh

Escape parentheses

---

.circleci/config.yml
scripts/create-pr.sh
scripts/helpers.sh

Reorder github release

---

scripts/release-github.sh

Remove last authenticated check

Remove last authenticated check

---

scripts/release-cocoapods.sh

Pull latest

---

scripts/create-pr.sh
scripts/helpers.sh
scripts/release-github.sh

Add create release logic

---

scripts/release-github.sh

Update release notes based on changelog

Update release notes based on changelog

---

PinwheelSDK.podspec

This reverts commit db98ada89df99f457b2e6441d6c43c15273468c7.
> Description here

Revert "Update binaries and CHANGELOG.md for version 3.3.0"
